apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "torchserve"
spec:
  predictor:
    pytorch:
      storageUri: "pvc://task-pv-claim/"
      resources:
        limits:
          memory: 4Gi
          nvidia.com/gpu: "1"
