apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: sloberta-model
spec:
  protocol: v2
  predictors:
    - graph:
        name: transformer
        implementation: HUGGINGFACE_SERVER
        modelUri: pvc://task-pv-claim/
        parameters:
          - name: task
            type: STRING
            value: question-answering
      name: default
      replicas: 1
