name: "sloberta"
backend: "python"

input [{
  name: "text"
  data_type: TYPE_STRING
  dims: [-1]
}]
input [{
  name: "question"
  data_type: TYPE_STRING
  dims: [-1]
}]
output [{
  name: "answer"
  data_type: TYPE_STRING
  dims: [-1]
}]