apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
spec:
  containers:
    - name: debug-container
      image: busybox
      command: ["/bin/sh", "-c", "sleep 10000"]
      volumeMounts:
        - mountPath: "/mnt"
          name: debug-volume
  volumes:
    - name: debug-volume
      persistentVolumeClaim:
        claimName: task-pv-claim
